//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStory.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenStory.Server.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error: {0}.
        /// </summary>
        public static string BootstrapConfigurationError {
            get {
                return ResourceManager.GetString("BootstrapConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus connection error: {0}.
        /// </summary>
        public static string BootstrapConnectionError {
            get {
                return ResourceManager.GetString("BootstrapConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the Nexus service: {0}.
        /// </summary>
        public static string BootstrapCouldNotConnectToNexus {
            get {
                return ResourceManager.GetString("BootstrapCouldNotConnectToNexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service hosting error: {0}.
        /// </summary>
        public static string BootstrapHostingError {
            get {
                return ResourceManager.GetString("BootstrapHostingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nexus service encountered a problem when processing your request: {0}.
        /// </summary>
        public static string BootstrapNexusGenericError {
            get {
                return ResourceManager.GetString("BootstrapNexusGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error: {0}.
        /// </summary>
        public static string BootstrapParseError {
            get {
                return ResourceManager.GetString("BootstrapParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nexus service refused the request. Are you sure your token is authorized?.
        /// </summary>
        public static string BootstrapRequestRefused {
            get {
                return ResourceManager.GetString("BootstrapRequestRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse nexus access token. Make sure you&apos;ve entered a valid GUID value under the parameter &apos;{0}&apos; (case-sensitive)..
        /// </summary>
        public static string BootstrapTokenParseError {
            get {
                return ResourceManager.GetString("BootstrapTokenParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse nexus URI string. Make sure you&apos;ve entered a valid service URI under the parameter &apos;{0}&apos; (case-sensitive)..
        /// </summary>
        public static string BootstrapUriParseError {
            get {
                return ResourceManager.GetString("BootstrapUriParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error: {0}.
        /// </summary>
        public static string BootstrapValidationError {
            get {
                return ResourceManager.GetString("BootstrapValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel identifier must be a non-negative integer..
        /// </summary>
        public static string ChannelIdMustBeNonNegative {
            get {
                return ResourceManager.GetString("ChannelIdMustBeNonNegative", resourceCulture);
            }
        }
    }
}
