//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenStory.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accept event has no subscribers..
        /// </summary>
        public static string AcceptEventHasNoSubscribers {
            get {
                return ResourceManager.GetString("AcceptEventHasNoSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided key array consist of exactly 32 bytes..
        /// </summary>
        public static string AesKeyMustBe32Bytes {
            get {
                return ResourceManager.GetString("AesKeyMustBe32Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array segment [{0},{1}] does not fit into the array&apos;s bounds..
        /// </summary>
        public static string BadArraySegmentEndpoints {
            get {
                return ResourceManager.GetString("BadArraySegmentEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array segment starting at {0} with length {1} does not fit into the array&apos;s bounds..
        /// </summary>
        public static string BadArraySegmentLength {
            get {
                return ResourceManager.GetString("BadArraySegmentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided capacity must be a non-negative integer..
        /// </summary>
        public static string CapacityMustBeNonNegative {
            get {
                return ResourceManager.GetString("CapacityMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided capacity must be a positive integer..
        /// </summary>
        public static string CapacityMustBePositive {
            get {
                return ResourceManager.GetString("CapacityMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided count argument must be a non-negative integer..
        /// </summary>
        public static string CountMustBeNonNegative {
            get {
                return ResourceManager.GetString("CountMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided count must be a positive integer..
        /// </summary>
        public static string CountMustBePositive {
            get {
                return ResourceManager.GetString("CountMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; : Parameter name duplicate after trimming white-space..
        /// </summary>
        public static string DuplicateParameterNames {
            get {
                return ResourceManager.GetString("DuplicateParameterNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the stream was reached..
        /// </summary>
        public static string EndOfStreamReached {
            get {
                return ResourceManager.GetString("EndOfStreamReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event cannot have more than one subscriber..
        /// </summary>
        public static string EventMustHaveOnlyOneSubscriber {
            get {
                return ResourceManager.GetString("EventMustHaveOnlyOneSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided number must be a valid key identifier..
        /// </summary>
        public static string InvalidKeyIdentifier {
            get {
                return ResourceManager.GetString("InvalidKeyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IV must be exactly 4 bytes long..
        /// </summary>
        public static string IvMustBe4Bytes {
            get {
                return ResourceManager.GetString("IvMustBe4Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided length must be a non-negative integer..
        /// </summary>
        public static string LengthMustBeNonNegative {
            get {
                return ResourceManager.GetString("LengthMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance does not have a socket attached to it.
        ///Please attach one before starting it..
        /// </summary>
        public static string NoSocketAttached {
            get {
                return ResourceManager.GetString("NoSocketAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided offset must be ahead of the current position..
        /// </summary>
        public static string OffsetMustBeAheadOfCurrentPosition {
            get {
                return ResourceManager.GetString("OffsetMustBeAheadOfCurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided offset must be a non-negative integer..
        /// </summary>
        public static string OffsetMustBeNonNegative {
            get {
                return ResourceManager.GetString("OffsetMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packet length must be a number larger than 2..
        /// </summary>
        public static string PacketLengthMustBeMoreThan2Bytes {
            get {
                return ResourceManager.GetString("PacketLengthMustBeMoreThan2Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided padding length must be a positive integer..
        /// </summary>
        public static string PaddingLengthMustBePositive {
            get {
                return ResourceManager.GetString("PaddingLengthMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The components of the provided point must be larger than Int16.MinValue..
        /// </summary>
        public static string PointComponentsMustBeLargerThanMinValue {
            get {
                return ResourceManager.GetString("PointComponentsMustBeLargerThanMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receive event has no subscribers..
        /// </summary>
        public static string ReceiveEventHasNoSubscribers {
            get {
                return ResourceManager.GetString("ReceiveEventHasNoSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segment must have at least {0} elements..
        /// </summary>
        public static string SegmentTooShort {
            get {
                return ResourceManager.GetString("SegmentTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session is already active..
        /// </summary>
        public static string SessionAlreadyActive {
            get {
                return ResourceManager.GetString("SessionAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network session is not open..
        /// </summary>
        public static string SessionIsNotActive {
            get {
                return ResourceManager.GetString("SessionIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session already has a socket attached to it..
        /// </summary>
        public static string SessionSocketAlreadyAttached {
            get {
                return ResourceManager.GetString("SessionSocketAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided table must consist of exactly 256 bytes..
        /// </summary>
        public static string ShuffleTableMustBe256Bytes {
            get {
                return ResourceManager.GetString("ShuffleTableMustBe256Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the provided string must be an even number..
        /// </summary>
        public static string StringLengthMustBeEven {
            get {
                return ResourceManager.GetString("StringLengthMustBeEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string must be shorter than the provided padding length..
        /// </summary>
        public static string StringMustBeShorterThanPaddingLength {
            get {
                return ResourceManager.GetString("StringMustBeShorterThanPaddingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string must consist only of hexadecimal digits..
        /// </summary>
        public static string StringMustContainOnlyHexDigits {
            get {
                return ResourceManager.GetString("StringMustContainOnlyHexDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided collection of bindings must contain exactly {0} elements..
        /// </summary>
        public static string WrongKeyBindingCount {
            get {
                return ResourceManager.GetString("WrongKeyBindingCount", resourceCulture);
            }
        }
    }
}
